Now using a config file snoopy.cfg for most of the parameters.
Major code modifications are still in gvars.h. Standard problem will be located
in cfg/*

Possible to init a problem using --with-problem=PROB in the configure script.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1279,6 +1279,7 @@ Optional Packages:
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-gcc-arch=<arch>  use architecture <arch> for gcc -march/-mtune,
                           instead of guessing
+  --with-problem=PBM	Problem generator from cfg/*
 
 Some influential environment variables:
   CC          C compiler command
@@ -6027,10 +6028,40 @@ if test "$ok" = "yes"; then
 fi
 
 #----------------------------------------------------
-#Create a gvars.h if none exist
+# if a problem is specified, create a gvars.h and snoopy.cfg
+# corresponding to this problem
+
+
+# Check whether --with-problem was given.
+if test "${with_problem+set}" = set; then
+  withval=$with_problem; problem=$withval
+else
+  problem=notset
+fi
+
+if test ! "$problem" = "notset"; then
+	# initialize the problem $problem
+	if test -e cfg/$problem/gvars.h; then
+		cp cfg/$problem/gvars.h src/
+		cp cfg/$problem/snoopy.cfg .
+	else
+		ls cfg/
+		{ { echo "$as_me:$LINENO: error: Invalid problem directory, valid names listed above" >&5
+echo "$as_me: error: Invalid problem directory, valid names listed above" >&2;}
+   { (exit 1); exit 1; }; }
+	fi
+fi
+
+#----------------------------------------------------
+#Create a code configuration if none exist
 if test ! -e src/gvars.h; then
-	echo "creating default src/gvars.h"
-	cp src/def/gvars_default.h src/gvars.h
+	echo "Using default problem"
+	problem=Default
+	cp -f cfg/default/gvars.h src/gvars.h
+fi
+if test ! -e snoopy.cfg; then
+	problem=Default
+	cp -f cfg/default/snoopy.cfg .
 fi
 
 #----------------------------------------------------
@@ -7073,6 +7104,7 @@ fi
 
 echo "*******************************************************"
 echo "I will use the following configuration:"
+echo " Problem:     $problem"
 echo " Compiler:    $CC"
 echo " MPI:         $MPI_ACTIVE"
 echo " FFTW MPI:    $FFTW_MPI_ACTIVE"
